### ISSUE TITLE
Fails on Windows (and Android) with "maxStorageBufferBindingSize exceeds limit. requested=1024MB, limit=128MB."

### ISSUE THREAD

**Issue by oscarbg** [mlc-ai/web-stable-diffusion#35]
Hi,
testing latest Chrome Canary on Windows and Android..
Win RTX 4070
Android Poco F3
both fails with:
"Find an error initializing the WebGPU device Error: Cannot initialize runtime because of requested maxStorageBufferBindingSize exceeds limit. requested=1024MB, limit=128MB."

also changed boot launch to:
--enable-dawn-features=disable_robustness
but that doesn't make a difference..
thanks..

**Comment by DustinBrett** [comment]
This sounds similar to my issue I noticed on web-llm.

[Canary decreased maxStorageBufferBindingSize limit? (!119)](https://github.com/mlc-ai/web-llm/issues/119)

**Comment by DustinBrett** [comment]
As of 116.0.5833.0 this is now fixed in Canary. So I think it was indeed browser related.

**Comment by oscarbg** [comment]
thanks! closing..

**Comment by fuerpy** [comment]
@oscarbg hi~I'm currently starting to port this project to run on android and I just finished reading through the walkthrough code. To my understanding, I change the target in the build function to mali or Adreno for android and can get a .so that will run on android, is this correct? Did you run it successfully on android please?
